// <auto-generated />
using CoderCarrer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoderCarrer.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20230410183641_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoderCarrer.Models.Vaga", b =>
                {
                    b.Property<int>("id_vaga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("data_vaga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descricao_vaga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("empresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("salario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_vaga");

                    b.ToTable("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
